package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AddJob generated by hbm2java
 */
public class AddJob  implements java.io.Serializable {


     private Integer idaddJob;
     private JobPriceList jobPriceList;
     private JobDuration jobDuration;
     private User user;
     private JobDisplayPhoto jobDisplayPhoto;
     private JobCategory jobCategory;
     private String title;
     private String description;
     private String tags;
     private String instructionsForBuyer;
     private Integer status;
     private Set orders = new HashSet(0);
     private Set jobFeedbacks = new HashSet(0);

    public AddJob() {
    }

	
    public AddJob(JobPriceList jobPriceList, JobDuration jobDuration, User user, JobDisplayPhoto jobDisplayPhoto, JobCategory jobCategory) {
        this.jobPriceList = jobPriceList;
        this.jobDuration = jobDuration;
        this.user = user;
        this.jobDisplayPhoto = jobDisplayPhoto;
        this.jobCategory = jobCategory;
    }
    public AddJob(JobPriceList jobPriceList, JobDuration jobDuration, User user, JobDisplayPhoto jobDisplayPhoto, JobCategory jobCategory, String title, String description, String tags, String instructionsForBuyer, Integer status, Set orders, Set jobFeedbacks) {
       this.jobPriceList = jobPriceList;
       this.jobDuration = jobDuration;
       this.user = user;
       this.jobDisplayPhoto = jobDisplayPhoto;
       this.jobCategory = jobCategory;
       this.title = title;
       this.description = description;
       this.tags = tags;
       this.instructionsForBuyer = instructionsForBuyer;
       this.status = status;
       this.orders = orders;
       this.jobFeedbacks = jobFeedbacks;
    }
   
    public Integer getIdaddJob() {
        return this.idaddJob;
    }
    
    public void setIdaddJob(Integer idaddJob) {
        this.idaddJob = idaddJob;
    }
    public JobPriceList getJobPriceList() {
        return this.jobPriceList;
    }
    
    public void setJobPriceList(JobPriceList jobPriceList) {
        this.jobPriceList = jobPriceList;
    }
    public JobDuration getJobDuration() {
        return this.jobDuration;
    }
    
    public void setJobDuration(JobDuration jobDuration) {
        this.jobDuration = jobDuration;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public JobDisplayPhoto getJobDisplayPhoto() {
        return this.jobDisplayPhoto;
    }
    
    public void setJobDisplayPhoto(JobDisplayPhoto jobDisplayPhoto) {
        this.jobDisplayPhoto = jobDisplayPhoto;
    }
    public JobCategory getJobCategory() {
        return this.jobCategory;
    }
    
    public void setJobCategory(JobCategory jobCategory) {
        this.jobCategory = jobCategory;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }
    public String getInstructionsForBuyer() {
        return this.instructionsForBuyer;
    }
    
    public void setInstructionsForBuyer(String instructionsForBuyer) {
        this.instructionsForBuyer = instructionsForBuyer;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getJobFeedbacks() {
        return this.jobFeedbacks;
    }
    
    public void setJobFeedbacks(Set jobFeedbacks) {
        this.jobFeedbacks = jobFeedbacks;
    }




}


