package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * CartHasProject generated by hbm2java
 */
public class CartHasProject  implements java.io.Serializable {


     private Integer idcartHasProject;
     private Projects projects;
     private Cart cart;
     private Double qty;
     private Integer isPurchase;
     private Double price;

    public CartHasProject() {
    }

	
    public CartHasProject(Projects projects, Cart cart) {
        this.projects = projects;
        this.cart = cart;
    }
    public CartHasProject(Projects projects, Cart cart, Double qty, Integer isPurchase, Double price) {
       this.projects = projects;
       this.cart = cart;
       this.qty = qty;
       this.isPurchase = isPurchase;
       this.price = price;
    }
   
    public Integer getIdcartHasProject() {
        return this.idcartHasProject;
    }
    
    public void setIdcartHasProject(Integer idcartHasProject) {
        this.idcartHasProject = idcartHasProject;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Integer getIsPurchase() {
        return this.isPurchase;
    }
    
    public void setIsPurchase(Integer isPurchase) {
        this.isPurchase = isPurchase;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


