package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idCategory;
     private SubCategory subCategory;
     private CategoryType categoryType;
     private Set projectses = new HashSet(0);

    public Category() {
    }

	
    public Category(SubCategory subCategory, CategoryType categoryType) {
        this.subCategory = subCategory;
        this.categoryType = categoryType;
    }
    public Category(SubCategory subCategory, CategoryType categoryType, Set projectses) {
       this.subCategory = subCategory;
       this.categoryType = categoryType;
       this.projectses = projectses;
    }
   
    public Integer getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public CategoryType getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(CategoryType categoryType) {
        this.categoryType = categoryType;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }




}


