package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CategoryType generated by hbm2java
 */
public class CategoryType  implements java.io.Serializable {


     private Integer idCategoryType;
     private String name;
     private Integer status;
     private Set categories = new HashSet(0);

    public CategoryType() {
    }

    public CategoryType(String name, Integer status, Set categories) {
       this.name = name;
       this.status = status;
       this.categories = categories;
    }
   
    public Integer getIdCategoryType() {
        return this.idCategoryType;
    }
    
    public void setIdCategoryType(Integer idCategoryType) {
        this.idCategoryType = idCategoryType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }




}


