package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Database1 generated by hbm2java
 */
public class Database1  implements java.io.Serializable {


     private Integer idDatabase;
     private String name;
     private Integer status;
     private Set projectses = new HashSet(0);

    public Database1() {
    }

    public Database1(String name, Integer status, Set projectses) {
       this.name = name;
       this.status = status;
       this.projectses = projectses;
    }
   
    public Integer getIdDatabase() {
        return this.idDatabase;
    }
    
    public void setIdDatabase(Integer idDatabase) {
        this.idDatabase = idDatabase;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }




}


