package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * JobCategory generated by hbm2java
 */
public class JobCategory  implements java.io.Serializable {


     private Integer idjobType;
     private String categoryName;
     private Integer status;
     private Set addJobs = new HashSet(0);

    public JobCategory() {
    }

    public JobCategory(String categoryName, Integer status, Set addJobs) {
       this.categoryName = categoryName;
       this.status = status;
       this.addJobs = addJobs;
    }
   
    public Integer getIdjobType() {
        return this.idjobType;
    }
    
    public void setIdjobType(Integer idjobType) {
        this.idjobType = idjobType;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getAddJobs() {
        return this.addJobs;
    }
    
    public void setAddJobs(Set addJobs) {
        this.addJobs = addJobs;
    }




}


