package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * JobDuration generated by hbm2java
 */
public class JobDuration  implements java.io.Serializable {


     private Integer idjobDuration;
     private String time;
     private Set addJobs = new HashSet(0);

    public JobDuration() {
    }

    public JobDuration(String time, Set addJobs) {
       this.time = time;
       this.addJobs = addJobs;
    }
   
    public Integer getIdjobDuration() {
        return this.idjobDuration;
    }
    
    public void setIdjobDuration(Integer idjobDuration) {
        this.idjobDuration = idjobDuration;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public Set getAddJobs() {
        return this.addJobs;
    }
    
    public void setAddJobs(Set addJobs) {
        this.addJobs = addJobs;
    }




}


