package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * JobDisplayPhoto generated by hbm2java
 */
public class JobDisplayPhoto  implements java.io.Serializable {


     private Integer idJobDisplayPhoto;
     private String path;
     private Set addJobs = new HashSet(0);

    public JobDisplayPhoto() {
    }

    public JobDisplayPhoto(String path, Set addJobs) {
       this.path = path;
       this.addJobs = addJobs;
    }
   
    public Integer getIdJobDisplayPhoto() {
        return this.idJobDisplayPhoto;
    }
    
    public void setIdJobDisplayPhoto(Integer idJobDisplayPhoto) {
        this.idJobDisplayPhoto = idJobDisplayPhoto;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set getAddJobs() {
        return this.addJobs;
    }
    
    public void setAddJobs(Set addJobs) {
        this.addJobs = addJobs;
    }




}


