package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * JobFeedback generated by hbm2java
 */
public class JobFeedback  implements java.io.Serializable {


     private Integer idJobFeedback;
     private User user;
     private AddJob addJob;
     private String feedbackTitle;
     private String feedback;
     private Integer rating;
     private String dateTime;
     private Integer status;

    public JobFeedback() {
    }

	
    public JobFeedback(User user, AddJob addJob) {
        this.user = user;
        this.addJob = addJob;
    }
    public JobFeedback(User user, AddJob addJob, String feedbackTitle, String feedback, Integer rating, String dateTime, Integer status) {
       this.user = user;
       this.addJob = addJob;
       this.feedbackTitle = feedbackTitle;
       this.feedback = feedback;
       this.rating = rating;
       this.dateTime = dateTime;
       this.status = status;
    }
   
    public Integer getIdJobFeedback() {
        return this.idJobFeedback;
    }
    
    public void setIdJobFeedback(Integer idJobFeedback) {
        this.idJobFeedback = idJobFeedback;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public AddJob getAddJob() {
        return this.addJob;
    }
    
    public void setAddJob(AddJob addJob) {
        this.addJob = addJob;
    }
    public String getFeedbackTitle() {
        return this.feedbackTitle;
    }
    
    public void setFeedbackTitle(String feedbackTitle) {
        this.feedbackTitle = feedbackTitle;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


