package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * JobPriceList generated by hbm2java
 */
public class JobPriceList  implements java.io.Serializable {


     private Integer idjobPriceList;
     private String price;
     private Set addJobs = new HashSet(0);

    public JobPriceList() {
    }

    public JobPriceList(String price, Set addJobs) {
       this.price = price;
       this.addJobs = addJobs;
    }
   
    public Integer getIdjobPriceList() {
        return this.idjobPriceList;
    }
    
    public void setIdjobPriceList(Integer idjobPriceList) {
        this.idjobPriceList = idjobPriceList;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public Set getAddJobs() {
        return this.addJobs;
    }
    
    public void setAddJobs(Set addJobs) {
        this.addJobs = addJobs;
    }




}


