package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer idMessage;
     private User userByIduserTo;
     private User userByIduserForm;
     private Set messageBodies = new HashSet(0);

    public Message() {
    }

	
    public Message(User userByIduserTo, User userByIduserForm) {
        this.userByIduserTo = userByIduserTo;
        this.userByIduserForm = userByIduserForm;
    }
    public Message(User userByIduserTo, User userByIduserForm, Set messageBodies) {
       this.userByIduserTo = userByIduserTo;
       this.userByIduserForm = userByIduserForm;
       this.messageBodies = messageBodies;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public User getUserByIduserTo() {
        return this.userByIduserTo;
    }
    
    public void setUserByIduserTo(User userByIduserTo) {
        this.userByIduserTo = userByIduserTo;
    }
    public User getUserByIduserForm() {
        return this.userByIduserForm;
    }
    
    public void setUserByIduserForm(User userByIduserForm) {
        this.userByIduserForm = userByIduserForm;
    }
    public Set getMessageBodies() {
        return this.messageBodies;
    }
    
    public void setMessageBodies(Set messageBodies) {
        this.messageBodies = messageBodies;
    }




}


