package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MessageBody generated by hbm2java
 */
public class MessageBody  implements java.io.Serializable {


     private Integer idMessageBody;
     private Message message;
     private String time;
     private String message_1;
     private Set msgBodyHasAttachments = new HashSet(0);

    public MessageBody() {
    }

	
    public MessageBody(Message message) {
        this.message = message;
    }
    public MessageBody(Message message, String time, String message_1, Set msgBodyHasAttachments) {
       this.message = message;
       this.time = time;
       this.message_1 = message_1;
       this.msgBodyHasAttachments = msgBodyHasAttachments;
    }
   
    public Integer getIdMessageBody() {
        return this.idMessageBody;
    }
    
    public void setIdMessageBody(Integer idMessageBody) {
        this.idMessageBody = idMessageBody;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getMessage_1() {
        return this.message_1;
    }
    
    public void setMessage_1(String message_1) {
        this.message_1 = message_1;
    }
    public Set getMsgBodyHasAttachments() {
        return this.msgBodyHasAttachments;
    }
    
    public void setMsgBodyHasAttachments(Set msgBodyHasAttachments) {
        this.msgBodyHasAttachments = msgBodyHasAttachments;
    }




}


