package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * MsgBodyHasAttachment generated by hbm2java
 */
public class MsgBodyHasAttachment  implements java.io.Serializable {


     private Integer idMsgBodyHasAttachment;
     private MessageBody messageBody;
     private String time;
     private String url;

    public MsgBodyHasAttachment() {
    }

	
    public MsgBodyHasAttachment(MessageBody messageBody) {
        this.messageBody = messageBody;
    }
    public MsgBodyHasAttachment(MessageBody messageBody, String time, String url) {
       this.messageBody = messageBody;
       this.time = time;
       this.url = url;
    }
   
    public Integer getIdMsgBodyHasAttachment() {
        return this.idMsgBodyHasAttachment;
    }
    
    public void setIdMsgBodyHasAttachment(Integer idMsgBodyHasAttachment) {
        this.idMsgBodyHasAttachment = idMsgBodyHasAttachment;
    }
    public MessageBody getMessageBody() {
        return this.messageBody;
    }
    
    public void setMessageBody(MessageBody messageBody) {
        this.messageBody = messageBody;
    }
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


