package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer idorder;
     private User userBySendOrderUser;
     private OrderDetails orderDetails;
     private User userByReceiverUser;
     private AddJob addJob;
     private Integer status;

    public Order() {
    }

	
    public Order(User userBySendOrderUser, OrderDetails orderDetails, User userByReceiverUser, AddJob addJob) {
        this.userBySendOrderUser = userBySendOrderUser;
        this.orderDetails = orderDetails;
        this.userByReceiverUser = userByReceiverUser;
        this.addJob = addJob;
    }
    public Order(User userBySendOrderUser, OrderDetails orderDetails, User userByReceiverUser, AddJob addJob, Integer status) {
       this.userBySendOrderUser = userBySendOrderUser;
       this.orderDetails = orderDetails;
       this.userByReceiverUser = userByReceiverUser;
       this.addJob = addJob;
       this.status = status;
    }
   
    public Integer getIdorder() {
        return this.idorder;
    }
    
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }
    public User getUserBySendOrderUser() {
        return this.userBySendOrderUser;
    }
    
    public void setUserBySendOrderUser(User userBySendOrderUser) {
        this.userBySendOrderUser = userBySendOrderUser;
    }
    public OrderDetails getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(OrderDetails orderDetails) {
        this.orderDetails = orderDetails;
    }
    public User getUserByReceiverUser() {
        return this.userByReceiverUser;
    }
    
    public void setUserByReceiverUser(User userByReceiverUser) {
        this.userByReceiverUser = userByReceiverUser;
    }
    public AddJob getAddJob() {
        return this.addJob;
    }
    
    public void setAddJob(AddJob addJob) {
        this.addJob = addJob;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


