package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private Integer idorderDetails;
     private String title;
     private String msgBody;
     private Set orders = new HashSet(0);

    public OrderDetails() {
    }

    public OrderDetails(String title, String msgBody, Set orders) {
       this.title = title;
       this.msgBody = msgBody;
       this.orders = orders;
    }
   
    public Integer getIdorderDetails() {
        return this.idorderDetails;
    }
    
    public void setIdorderDetails(Integer idorderDetails) {
        this.idorderDetails = idorderDetails;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getMsgBody() {
        return this.msgBody;
    }
    
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


