package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer idPayment;
     private User user;
     private Integer projectCount;
     private Double totalAmount;
     private String dateTime;
     private int emailStatus;
     private Set paymentHasProjectses = new HashSet(0);

    public Payment() {
    }

	
    public Payment(User user, int emailStatus) {
        this.user = user;
        this.emailStatus = emailStatus;
    }
    public Payment(User user, Integer projectCount, Double totalAmount, String dateTime, int emailStatus, Set paymentHasProjectses) {
       this.user = user;
       this.projectCount = projectCount;
       this.totalAmount = totalAmount;
       this.dateTime = dateTime;
       this.emailStatus = emailStatus;
       this.paymentHasProjectses = paymentHasProjectses;
    }
   
    public Integer getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(Integer idPayment) {
        this.idPayment = idPayment;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getProjectCount() {
        return this.projectCount;
    }
    
    public void setProjectCount(Integer projectCount) {
        this.projectCount = projectCount;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    public int getEmailStatus() {
        return this.emailStatus;
    }
    
    public void setEmailStatus(int emailStatus) {
        this.emailStatus = emailStatus;
    }
    public Set getPaymentHasProjectses() {
        return this.paymentHasProjectses;
    }
    
    public void setPaymentHasProjectses(Set paymentHasProjectses) {
        this.paymentHasProjectses = paymentHasProjectses;
    }




}


