package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ProHasView generated by hbm2java
 */
public class ProHasView  implements java.io.Serializable {


     private Integer idproHasView;
     private Integer click;
     private Integer order;
     private Integer rating;
     private Set views = new HashSet(0);

    public ProHasView() {
    }

    public ProHasView(Integer click, Integer order, Integer rating, Set views) {
       this.click = click;
       this.order = order;
       this.rating = rating;
       this.views = views;
    }
   
    public Integer getIdproHasView() {
        return this.idproHasView;
    }
    
    public void setIdproHasView(Integer idproHasView) {
        this.idproHasView = idproHasView;
    }
    public Integer getClick() {
        return this.click;
    }
    
    public void setClick(Integer click) {
        this.click = click;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }
    public Set getViews() {
        return this.views;
    }
    
    public void setViews(Set views) {
        this.views = views;
    }




}


