package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects  implements java.io.Serializable {


     private Integer idprojects;
     private UploadFile uploadFile;
     private SubCategory subCategory;
     private Category category;
     private User user;
     private UploadDemo uploadDemo;
     private UploadPic uploadPic;
     private Database1 database1;
     private String projectName;
     private String price;
     private String description;
     private String proLan;
     private Integer status;
     private Set cartHasProjects = new HashSet(0);
     private Set paymentHasProjectses = new HashSet(0);
     private Set views = new HashSet(0);

    public Projects() {
    }

	
    public Projects(UploadFile uploadFile, SubCategory subCategory, Category category, User user, UploadDemo uploadDemo, UploadPic uploadPic, Database1 database1) {
        this.uploadFile = uploadFile;
        this.subCategory = subCategory;
        this.category = category;
        this.user = user;
        this.uploadDemo = uploadDemo;
        this.uploadPic = uploadPic;
        this.database1 = database1;
    }
    public Projects(UploadFile uploadFile, SubCategory subCategory, Category category, User user, UploadDemo uploadDemo, UploadPic uploadPic, Database1 database1, String projectName, String price, String description, String proLan, Integer status, Set cartHasProjects, Set paymentHasProjectses, Set views) {
       this.uploadFile = uploadFile;
       this.subCategory = subCategory;
       this.category = category;
       this.user = user;
       this.uploadDemo = uploadDemo;
       this.uploadPic = uploadPic;
       this.database1 = database1;
       this.projectName = projectName;
       this.price = price;
       this.description = description;
       this.proLan = proLan;
       this.status = status;
       this.cartHasProjects = cartHasProjects;
       this.paymentHasProjectses = paymentHasProjectses;
       this.views = views;
    }
   
    public Integer getIdprojects() {
        return this.idprojects;
    }
    
    public void setIdprojects(Integer idprojects) {
        this.idprojects = idprojects;
    }
    public UploadFile getUploadFile() {
        return this.uploadFile;
    }
    
    public void setUploadFile(UploadFile uploadFile) {
        this.uploadFile = uploadFile;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public UploadDemo getUploadDemo() {
        return this.uploadDemo;
    }
    
    public void setUploadDemo(UploadDemo uploadDemo) {
        this.uploadDemo = uploadDemo;
    }
    public UploadPic getUploadPic() {
        return this.uploadPic;
    }
    
    public void setUploadPic(UploadPic uploadPic) {
        this.uploadPic = uploadPic;
    }
    public Database1 getDatabase1() {
        return this.database1;
    }
    
    public void setDatabase1(Database1 database1) {
        this.database1 = database1;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getProLan() {
        return this.proLan;
    }
    
    public void setProLan(String proLan) {
        this.proLan = proLan;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCartHasProjects() {
        return this.cartHasProjects;
    }
    
    public void setCartHasProjects(Set cartHasProjects) {
        this.cartHasProjects = cartHasProjects;
    }
    public Set getPaymentHasProjectses() {
        return this.paymentHasProjectses;
    }
    
    public void setPaymentHasProjectses(Set paymentHasProjectses) {
        this.paymentHasProjectses = paymentHasProjectses;
    }
    public Set getViews() {
        return this.views;
    }
    
    public void setViews(Set views) {
        this.views = views;
    }




}


