package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer idSubCategory;
     private String name;
     private Integer status;
     private Set projectses = new HashSet(0);
     private Set categories = new HashSet(0);

    public SubCategory() {
    }

    public SubCategory(String name, Integer status, Set projectses, Set categories) {
       this.name = name;
       this.status = status;
       this.projectses = projectses;
       this.categories = categories;
    }
   
    public Integer getIdSubCategory() {
        return this.idSubCategory;
    }
    
    public void setIdSubCategory(Integer idSubCategory) {
        this.idSubCategory = idSubCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }




}


