package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer iduserLogin;
     private UserType userType;
     private User user;
     private String uname;
     private String password;
     private String location;
     private String jobLocation;
     private Integer status;
     private String demoFileLocation;
     private Set userLoginDetailses = new HashSet(0);

    public UserLogin() {
    }

	
    public UserLogin(UserType userType, User user) {
        this.userType = userType;
        this.user = user;
    }
    public UserLogin(UserType userType, User user, String uname, String password, String location, String jobLocation, Integer status, String demoFileLocation, Set userLoginDetailses) {
       this.userType = userType;
       this.user = user;
       this.uname = uname;
       this.password = password;
       this.location = location;
       this.jobLocation = jobLocation;
       this.status = status;
       this.demoFileLocation = demoFileLocation;
       this.userLoginDetailses = userLoginDetailses;
    }
   
    public Integer getIduserLogin() {
        return this.iduserLogin;
    }
    
    public void setIduserLogin(Integer iduserLogin) {
        this.iduserLogin = iduserLogin;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getJobLocation() {
        return this.jobLocation;
    }
    
    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getDemoFileLocation() {
        return this.demoFileLocation;
    }
    
    public void setDemoFileLocation(String demoFileLocation) {
        this.demoFileLocation = demoFileLocation;
    }
    public Set getUserLoginDetailses() {
        return this.userLoginDetailses;
    }
    
    public void setUserLoginDetailses(Set userLoginDetailses) {
        this.userLoginDetailses = userLoginDetailses;
    }




}


