package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * UserTypeHasUserPage generated by hbm2java
 */
public class UserTypeHasUserPage  implements java.io.Serializable {


     private Integer idUserTypeHasUserPage;
     private UserType userType;
     private UserPage userPage;

    public UserTypeHasUserPage() {
    }

    public UserTypeHasUserPage(UserType userType, UserPage userPage) {
       this.userType = userType;
       this.userPage = userPage;
    }
   
    public Integer getIdUserTypeHasUserPage() {
        return this.idUserTypeHasUserPage;
    }
    
    public void setIdUserTypeHasUserPage(Integer idUserTypeHasUserPage) {
        this.idUserTypeHasUserPage = idUserTypeHasUserPage;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public UserPage getUserPage() {
        return this.userPage;
    }
    
    public void setUserPage(UserPage userPage) {
        this.userPage = userPage;
    }




}


