package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserPage generated by hbm2java
 */
public class UserPage  implements java.io.Serializable {


     private Integer iduserPage;
     private String url;
     private String pageName;
     private Integer status;
     private Set userTypeHasUserPages = new HashSet(0);

    public UserPage() {
    }

    public UserPage(String url, String pageName, Integer status, Set userTypeHasUserPages) {
       this.url = url;
       this.pageName = pageName;
       this.status = status;
       this.userTypeHasUserPages = userTypeHasUserPages;
    }
   
    public Integer getIduserPage() {
        return this.iduserPage;
    }
    
    public void setIduserPage(Integer iduserPage) {
        this.iduserPage = iduserPage;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getPageName() {
        return this.pageName;
    }
    
    public void setPageName(String pageName) {
        this.pageName = pageName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getUserTypeHasUserPages() {
        return this.userTypeHasUserPages;
    }
    
    public void setUserTypeHasUserPages(Set userTypeHasUserPages) {
        this.userTypeHasUserPages = userTypeHasUserPages;
    }




}


