package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private String fname;
     private String lname;
     private String email;
     private String description;
     private Set ordersForSendOrderUser = new HashSet(0);
     private Set jobFeedbacks = new HashSet(0);
     private Set payments = new HashSet(0);
     private Set userLogins = new HashSet(0);
     private Set carts = new HashSet(0);
     private Set addJobs = new HashSet(0);
     private Set messagesForIduserForm = new HashSet(0);
     private Set ordersForReceiverUser = new HashSet(0);
     private Set messagesForIduserTo = new HashSet(0);
     private Set views = new HashSet(0);
     private Set vacations = new HashSet(0);
     private Set projectses = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, String email, String description, Set ordersForSendOrderUser, Set jobFeedbacks, Set payments, Set userLogins, Set carts, Set addJobs, Set messagesForIduserForm, Set ordersForReceiverUser, Set messagesForIduserTo, Set views, Set vacations, Set projectses) {
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.description = description;
       this.ordersForSendOrderUser = ordersForSendOrderUser;
       this.jobFeedbacks = jobFeedbacks;
       this.payments = payments;
       this.userLogins = userLogins;
       this.carts = carts;
       this.addJobs = addJobs;
       this.messagesForIduserForm = messagesForIduserForm;
       this.ordersForReceiverUser = ordersForReceiverUser;
       this.messagesForIduserTo = messagesForIduserTo;
       this.views = views;
       this.vacations = vacations;
       this.projectses = projectses;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrdersForSendOrderUser() {
        return this.ordersForSendOrderUser;
    }
    
    public void setOrdersForSendOrderUser(Set ordersForSendOrderUser) {
        this.ordersForSendOrderUser = ordersForSendOrderUser;
    }
    public Set getJobFeedbacks() {
        return this.jobFeedbacks;
    }
    
    public void setJobFeedbacks(Set jobFeedbacks) {
        this.jobFeedbacks = jobFeedbacks;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getAddJobs() {
        return this.addJobs;
    }
    
    public void setAddJobs(Set addJobs) {
        this.addJobs = addJobs;
    }
    public Set getMessagesForIduserForm() {
        return this.messagesForIduserForm;
    }
    
    public void setMessagesForIduserForm(Set messagesForIduserForm) {
        this.messagesForIduserForm = messagesForIduserForm;
    }
    public Set getOrdersForReceiverUser() {
        return this.ordersForReceiverUser;
    }
    
    public void setOrdersForReceiverUser(Set ordersForReceiverUser) {
        this.ordersForReceiverUser = ordersForReceiverUser;
    }
    public Set getMessagesForIduserTo() {
        return this.messagesForIduserTo;
    }
    
    public void setMessagesForIduserTo(Set messagesForIduserTo) {
        this.messagesForIduserTo = messagesForIduserTo;
    }
    public Set getViews() {
        return this.views;
    }
    
    public void setViews(Set views) {
        this.views = views;
    }
    public Set getVacations() {
        return this.vacations;
    }
    
    public void setVacations(Set vacations) {
        this.vacations = vacations;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }




}


