package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * Vacation generated by hbm2java
 */
public class Vacation  implements java.io.Serializable {


     private Integer idvacation;
     private User user;
     private VacationDuration vacationDuration;
     private Integer status;

    public Vacation() {
    }

	
    public Vacation(User user, VacationDuration vacationDuration) {
        this.user = user;
        this.vacationDuration = vacationDuration;
    }
    public Vacation(User user, VacationDuration vacationDuration, Integer status) {
       this.user = user;
       this.vacationDuration = vacationDuration;
       this.status = status;
    }
   
    public Integer getIdvacation() {
        return this.idvacation;
    }
    
    public void setIdvacation(Integer idvacation) {
        this.idvacation = idvacation;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public VacationDuration getVacationDuration() {
        return this.vacationDuration;
    }
    
    public void setVacationDuration(VacationDuration vacationDuration) {
        this.vacationDuration = vacationDuration;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


