package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA



/**
 * View generated by hbm2java
 */
public class View  implements java.io.Serializable {


     private Integer idview;
     private Projects projects;
     private User user;
     private ViewType viewType;
     private ProHasView proHasView;

    public View() {
    }

    public View(Projects projects, User user, ViewType viewType, ProHasView proHasView) {
       this.projects = projects;
       this.user = user;
       this.viewType = viewType;
       this.proHasView = proHasView;
    }
   
    public Integer getIdview() {
        return this.idview;
    }
    
    public void setIdview(Integer idview) {
        this.idview = idview;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public ViewType getViewType() {
        return this.viewType;
    }
    
    public void setViewType(ViewType viewType) {
        this.viewType = viewType;
    }
    public ProHasView getProHasView() {
        return this.proHasView;
    }
    
    public void setProHasView(ProHasView proHasView) {
        this.proHasView = proHasView;
    }




}


