package DB;
// Generated Mar 3, 2015 12:28:18 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ViewType generated by hbm2java
 */
public class ViewType  implements java.io.Serializable {


     private Integer idviewType;
     private String typeName;
     private Set views = new HashSet(0);

    public ViewType() {
    }

    public ViewType(String typeName, Set views) {
       this.typeName = typeName;
       this.views = views;
    }
   
    public Integer getIdviewType() {
        return this.idviewType;
    }
    
    public void setIdviewType(Integer idviewType) {
        this.idviewType = idviewType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set getViews() {
        return this.views;
    }
    
    public void setViews(Set views) {
        this.views = views;
    }




}


